### ISSUE TITLE
Scroll position not always reset to top of page when changing section

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-docs-v2#56]
To recreate:
- in Firefox 71 (Chrome does seem to reset the scroll position)
- go to: https://docs-beta.ipfs.io
- scroll to bottom
- click on **Concepts** in the sidebar nav
- I see the page still scrolled to the bottom, so I see _Still don't see what your looking for_ rather than the concepts intro which is scolled out of view above.

<img width="1392" alt="Screenshot 2020-01-07 at 13 42 06" src="https://user-images.githubusercontent.com/58871/71899437-a2b46780-3153-11ea-8153-a265909ec391.png">

**Comment by johnnymatthews** [comment]
This bug is also present on the [VuePress documentation site](https://vuepress.vuejs.org/guide/).

![firefox-bug](https://user-images.githubusercontent.com/9611008/71909996-14ce8180-313f-11ea-95ec-d4b54a1074b7.gif)

**Comment by jessicaschilling** [comment]
I thought this was discussed/fixed a while back? @cwaring - does this ring any bells?

**Comment by cwaring** [comment]
Issue moved to [ipfs/docs #417](https://github.com/ipfs/docs/issues/417) via [**ZenHub**](https://www.zenhub.com/)
